package setup

import (
	"errors"
	"fmt"
	"net"
	"strings"
)

// Domain setup, run once when the box first comes up. The operator gives a domain (their own, or a
// name under localghost.ai); ghost.secd checks the DNS actually points at this box BEFORE writing
// any nginx config, so you never stand up a listener for a name that does not resolve to you.
//
// Privacy note, stated up front because it is a real trade: putting the box behind a public domain
// makes the box's existence and address resolvable, and whoever runs the DNS zone (LocalGhost, for a
// *.localghost.ai name) can see the box's IP. That is the opposite of the QR enrollment path, which
// touches no servers. So a public domain is OPTIONAL and for remote access convenience; the LAN +
// QR path stays the zero-server default. An operator who wants no public footprint uses their own
// domain with private DNS, or no domain at all and reaches the box over VPN.

type DomainConfig struct {
	Domain     string // e.g. "vlad.localghost.ai" or a self-owned domain
	PublicIPv4 string // the box's public address the domain must resolve to
}

var (
	ErrNoDomain      = errors.New("no domain given")
	ErrDNSMismatch   = errors.New("domain does not resolve to this box")
	ErrDNSUnresolved = errors.New("domain does not resolve at all yet")
)

// VerifyDNS checks the domain's A record points at the box's public IP. Returns a clear error the
// setup UI can show ("add an A record for X -> Y, then retry"). lookup is injectable for tests.
func (d DomainConfig) VerifyDNS(lookup func(host string) ([]net.IP, error)) error {
	if strings.TrimSpace(d.Domain) == "" {
		return ErrNoDomain
	}
	ips, err := lookup(d.Domain)
	if err != nil || len(ips) == 0 {
		return fmt.Errorf("%w: %s", ErrDNSUnresolved, d.Domain)
	}
	want := net.ParseIP(d.PublicIPv4)
	for _, ip := range ips {
		if ip.Equal(want) {
			return nil
		}
	}
	return fmt.Errorf("%w: %s resolves elsewhere, expected %s", ErrDNSMismatch, d.Domain, d.PublicIPv4)
}

// NginxConfig renders the edge config once DNS verifies. nginx terminates public TLS for the domain
// and forwards to ghost.secd on loopback; it does NOT see decrypted account data or do auth, that is
// all ghost.secd. TLS certs are obtained separately (ACME); this is the server block.
func (d DomainConfig) NginxConfig(ghostSecdAddr string) string {
	return fmt.Sprintf(`# generated by ghost.secd , do not edit by hand
server {
    listen 443 ssl;
    http2 on;
    server_name %[1]s;

    # Give away nothing about the software here. server_tokens off drops the nginx VERSION from the
    # Server header and from any default error page. (The bare string "Server: nginx" can only be
    # removed with the headers-more module; it is near-zero signal , nginx serves a large fraction of
    # the web , but if that module is present, add:  more_clear_headers Server;)
    server_tokens off;

    # The box is its own CA. This server cert is self-issued and the phone PINS it (the
    # fingerprint travels in the enrollment QR), so there is no Let's Encrypt, no ACME, no port 80.
    ssl_certificate     /etc/ghost/ca/box-server.pem;
    ssl_certificate_key /etc/ghost/ca/box-server-key.pem;

    # ACCESS LAYER. A device cert issued by THIS box's CA is the access key, but its ABSENCE or
    # INVALIDITY must never be distinguishable from the box being down. So verification is OPTIONAL at
    # the TLS layer (a certless client still completes the handshake, otherwise the handshake failure
    # itself would be a signal), and whether the cert verified is decided INSIDE, collapsing to the
    # same 503 as everything else. There is no public location that answers anything but 503.
    ssl_client_certificate /etc/ghost/ca/devices-ca.pem;  # the box CA bundle
    ssl_verify_client      optional;                      # NEVER 'on' , a handshake reject is a tell

    # APPEARS-DOWN, TOTAL. Every request , no cert, a broken or forged cert, a valid cert, a wrong PIN,
    # an expired token, a muted poll, a genuinely-off daemon, an unknown path , returns the SAME plain
    # 503. From outside, the only fact observable is "this host answers TLS on 443 and says the service
    # is unavailable". That is true of countless servers and reveals nothing: not that LocalGhost runs
    # here, not that a box is enrolled, not whether your cert is good, not whether the daemon is up.
    # It is deliberately hard to debug from the outside , which is the point.
    proxy_intercept_errors on;
    # Every nginx-generated status is folded in too , 405 (method), 408 (timeout), 413 (body too
    # large), 414/431 (long URL/headers), 500/501/507 , or a prober could distinguish, e.g., "this
    # host has a request-size limit" (413) from the flat 503. One status, no matter what you send.
    error_page 400 401 403 404 405 408 413 414 431 495 496 497 500 501 502 503 504 507 = @down;

    # Camera uploads: photos are multi-MB, videos run to hundreds of MB (a 4K phone clip is ~400MB+).
    # nginx's DEFAULT client_max_body_size is 1m, which bounced every photo with a 413 BEFORE it
    # reached ghost.secd , box journal empty while the app saw failures, the worst kind of silent.
    # 4g matches secd's own uploadMaxBytes cap; secd remains the real enforcer, nginx must not
    # undercut it. Only enrolled devices (valid device cert + live session) get past the 503 wall,
    # so the size limit is a bound for trusted phones, not an abuse surface.
    client_max_body_size 4g;

    location @down {
        # One plain, standard 503 for everything. We supply our own generic body so nginx never renders
        # its default error page (whose footer prints "nginx"); it names neither LocalGhost nor nginx.
        default_type text/html;
        return 503 "<!doctype html><title>503 Service Unavailable</title>\n<h1>Service Unavailable</h1>\n";
    }

    # There is NO public endpoint , not even enrolment. Enrolment is a LAN / first-contact action done
    # entirely by SCANNING the box's QR: the box generates the device keypair and the QR carries the
    # signed device certificate AND its key (an offline, screen-to-camera transfer), so the phone is
    # enrolled by the scan alone , it never makes a certless call to get a cert. The public domain
    # therefore never needs a certless door. A device with a valid cert proxies through; anyone else ,
    # no cert, bad cert, wrong path , gets the identical 503.
    location / {
        if ($ssl_client_verify != SUCCESS) { return 503; }
        # secd serves plain HTTP on loopback , nginx already terminated the public TLS and this hop
        # never leaves the box (127.0.0.1 on the encrypted host). http:// here, not https://, or nginx
        # speaks TLS to a plaintext server and every proxied request fails into the same 503.
        # STREAM uploads straight through. nginx's default (proxy_request_buffering on) spools the
        # whole request body to a temp file on the OS DISK before forwarding , which would put every
        # photo and video, PLAINTEXT, on the unencrypted disk in /var/lib/nginx tmp before it ever
        # reaches the encrypted volume. Buffering OFF means bytes flow phone -> nginx -> secd ->
        # encrypted volume and never rest anywhere else. 1.1 to the upstream so the stream can be
        # chunked (1.0 cannot carry a body without a length).
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_pass http://%[2]s;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Client-Cert  $ssl_client_escaped_cert; # ghost.secd binds device -> account
        # (no proxy_ssl_* here , the upstream is plain http on loopback; account auth is enforced in secd)
    }
}
`, d.Domain, ghostSecdAddr)
}
