package setup

import (
	"errors"
	"fmt"
	"net"
	"strings"
)

// Domain setup, run once when the box first comes up. The operator gives a domain (their own, or a
// name under localghost.ai); ghost.secd checks the DNS actually points at this box BEFORE writing
// any nginx config, so you never stand up a listener for a name that does not resolve to you.
//
// Privacy note, stated up front because it is a real trade: putting the box behind a public domain
// makes the box's existence and address resolvable, and whoever runs the DNS zone (LocalGhost, for a
// *.localghost.ai name) can see the box's IP. That is the opposite of the QR enrollment path, which
// touches no servers. So a public domain is OPTIONAL and for remote access convenience; the LAN +
// QR path stays the zero-server default. An operator who wants no public footprint uses their own
// domain with private DNS, or no domain at all and reaches the box over VPN.

type DomainConfig struct {
	Domain     string // e.g. "vlad.localghost.ai" or a self-owned domain
	PublicIPv4 string // the box's public address the domain must resolve to
}

var (
	ErrNoDomain      = errors.New("no domain given")
	ErrDNSMismatch   = errors.New("domain does not resolve to this box")
	ErrDNSUnresolved = errors.New("domain does not resolve at all yet")
)

// VerifyDNS checks the domain's A record points at the box's public IP. Returns a clear error the
// setup UI can show ("add an A record for X -> Y, then retry"). lookup is injectable for tests.
func (d DomainConfig) VerifyDNS(lookup func(host string) ([]net.IP, error)) error {
	if strings.TrimSpace(d.Domain) == "" {
		return ErrNoDomain
	}
	ips, err := lookup(d.Domain)
	if err != nil || len(ips) == 0 {
		return fmt.Errorf("%w: %s", ErrDNSUnresolved, d.Domain)
	}
	want := net.ParseIP(d.PublicIPv4)
	for _, ip := range ips {
		if ip.Equal(want) {
			return nil
		}
	}
	return fmt.Errorf("%w: %s resolves elsewhere, expected %s", ErrDNSMismatch, d.Domain, d.PublicIPv4)
}

// NginxConfig renders the edge config once DNS verifies. nginx terminates public TLS for the domain
// and forwards to ghost.secd on loopback; it does NOT see decrypted account data or do auth, that is
// all ghost.secd. TLS certs are obtained separately (ACME); this is the server block.
func (d DomainConfig) NginxConfig(ghostSecdAddr string) string {
	return fmt.Sprintf(`# generated by ghost.secd , do not edit by hand
server {
    listen 443 ssl http2;
    server_name %[1]s;

    # The box is its own CA. This server cert is self-issued and the phone PINS it (the
    # fingerprint travels in the enrollment QR), so there is no Let's Encrypt, no ACME, no port 80.
    ssl_certificate     /etc/ghost/ca/box-server.pem;
    ssl_certificate_key /etc/ghost/ca/box-server-key.pem;

    # ACCESS LAYER, before any account or PIN: a device cert issued by THIS box's CA is the access
    # key. We set verification to OPTIONAL at the server level so the ONE bootstrap endpoint ,
    # enrolment , can be reached by a device that does not have a cert yet (that call is how it gets
    # one). Every other location REQUIRES a verified cert, enforced per-location below. A scanner
    # hitting the public IP can reach only /v1/enroll, and that is gated by the one-time pairing
    # code (rate-limited, locks out). Reachability is not access.
    ssl_client_certificate /etc/ghost/ca/devices-ca.pem;  # the box CA bundle
    ssl_verify_client      optional;                      # required is enforced per-location

    # Enrolment bootstrap: no client cert yet (the device is getting one). Still TLS, still pinned by
    # the phone, still gated by the one-time pairing code inside ghost.secd.
    location = /v1/enroll {
        proxy_pass https://%[2]s;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_ssl_verify off;
    }

    # Everything else: reject anyone whose device cert did not verify against the box CA, at the edge,
    # before the request reaches ghost.secd.
    location / {
        if ($ssl_client_verify != SUCCESS) { return 403; }
        proxy_pass https://%[2]s;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Client-Cert  $ssl_client_escaped_cert; # ghost.secd binds device -> account
        proxy_ssl_verify off; # ghost.secd presents the box's own cert; account auth is enforced there
    }
}
`, d.Domain, ghostSecdAddr)
}
